Repository SWM-YouQuiz/Quiz-Service, pull requests merged in 2023-08, with the labels that each got.

#17 [YOUQ-84] 챕터 CRUD API 구현
  src/main/kotlin/com/youquiz/quiz/domain/Chapter.kt
  src/main/kotlin/com/youquiz/quiz/dto/ChapterResponse.kt
  src/main/kotlin/com/youquiz/quiz/dto/CreateChapterRequest.kt
  src/main/kotlin/com/youquiz/quiz/dto/UpdateChapterRequest.kt
  src/main/kotlin/com/youquiz/quiz/exception/ChapterNotFoundException.kt
  src/main/kotlin/com/youquiz/quiz/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/youquiz/quiz/handler/ChapterHandler.kt
  src/main/kotlin/com/youquiz/quiz/repository/ChapterRepository.kt
  src/main/kotlin/com/youquiz/quiz/router/ChapterRouter.kt
  src/main/kotlin/com/youquiz/quiz/service/ChapterService.kt
  src/test/kotlin/com/youquiz/quiz/controller/ChapterControllerTest.kt
  src/test/kotlin/com/youquiz/quiz/fixture/ChapterFixture.kt
  src/test/kotlin/com/youquiz/quiz/service/ChapterServiceTest.kt
  src/test/kotlin/com/youquiz/quiz/util/TestUtil.kt
Labels: Feat

#18 [YOUQ-67] 코스 CRUD API 구현
  src/main/kotlin/com/youquiz/quiz/domain/Course.kt
  src/main/kotlin/com/youquiz/quiz/dto/CourseResponse.kt
  src/main/kotlin/com/youquiz/quiz/dto/CreateCourseRequest.kt
  src/main/kotlin/com/youquiz/quiz/dto/UpdateCourseByIdRequest.kt
  src/main/kotlin/com/youquiz/quiz/exception/CourseNotFoundException.kt
  src/main/kotlin/com/youquiz/quiz/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/youquiz/quiz/handler/CourseHandler.kt
  src/main/kotlin/com/youquiz/quiz/repository/CourseRepository.kt
  src/main/kotlin/com/youquiz/quiz/router/CourseRouter.kt
  src/main/kotlin/com/youquiz/quiz/service/CourseService.kt
  src/test/kotlin/com/youquiz/quiz/controller/CourseControllerTest.kt
  src/test/kotlin/com/youquiz/quiz/fixture/CourseFixture.kt
  src/test/kotlin/com/youquiz/quiz/service/CourseServiceTest.kt
Labels: Feat

#20 [YOUQ-122] 퀴즈 수정 및 삭제 API 구현
  src/main/kotlin/com/youquiz/quiz/dto/UpdateQuizByIdRequest.kt
  src/main/kotlin/com/youquiz/quiz/exception/PermissionDeniedException.kt
  src/main/kotlin/com/youquiz/quiz/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/youquiz/quiz/handler/QuizHandler.kt
  src/main/kotlin/com/youquiz/quiz/router/QuizRouter.kt
  src/main/kotlin/com/youquiz/quiz/service/QuizService.kt
  src/test/kotlin/com/youquiz/quiz/config/ProjectConfiguration.kt
  src/test/kotlin/com/youquiz/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/youquiz/quiz/fixture/QuizFixture.kt
  src/test/kotlin/com/youquiz/quiz/service/ChapterServiceTest.kt
  src/test/kotlin/com/youquiz/quiz/service/CourseServiceTest.kt
  src/test/kotlin/com/youquiz/quiz/service/QuizServiceTest.kt
Labels: Feat

#23 [#22] 퀴즈 단일 조회 API 구현
  src/main/kotlin/com/youquiz/quiz/handler/QuizHandler.kt
  src/main/kotlin/com/youquiz/quiz/router/QuizRouter.kt
  src/main/kotlin/com/youquiz/quiz/service/QuizService.kt
  src/test/kotlin/com/youquiz/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/youquiz/quiz/service/QuizServiceTest.kt
Labels: Feat

#25 [#24] 퀴즈 페이징 조회 API 구현
  src/main/kotlin/com/youquiz/quiz/handler/QuizHandler.kt
  src/main/kotlin/com/youquiz/quiz/repository/QuizRepository.kt
  src/main/kotlin/com/youquiz/quiz/service/QuizService.kt
  src/test/kotlin/com/youquiz/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/youquiz/quiz/fixture/CommonFixture.kt
  src/test/kotlin/com/youquiz/quiz/service/QuizServiceTest.kt
Labels: Feat

#28 [YOUQ-123] Jenkins CI 연동
  Dockerfile
  Jenkinsfile
Labels: CI / CD

#29 [#26] 정답률 필터링 기능이 포함된 챕터별 퀴즈 페이징 조회 API 구현
  src/main/kotlin/com/quizit/quiz/handler/QuizHandler.kt
  src/main/kotlin/com/quizit/quiz/repository/QuizRepository.kt
  src/main/kotlin/com/quizit/quiz/router/QuizRouter.kt
  src/main/kotlin/com/quizit/quiz/service/QuizService.kt
  src/test/kotlin/com/quizit/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/quizit/quiz/service/QuizServiceTest.kt
Labels: Feat

#31 모든 API 엔드포인트 prefix 수정
  src/main/kotlin/com/quizit/quiz/global/config/SecurityConfiguration.kt
  src/main/kotlin/com/quizit/quiz/router/ChapterRouter.kt
  src/main/kotlin/com/quizit/quiz/router/CourseRouter.kt
  src/main/kotlin/com/quizit/quiz/router/QuizRouter.kt
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/kotlin/com/quizit/quiz/util/BaseControllerTest.kt
Labels: Fix, Feat

#32 Fix: WebClient Endpoint 수정
  src/main/kotlin/com/quizit/quiz/adapter/client/UserClient.kt
Labels: Fix

#36 [YOUQ-131] 문제 지문 기반 퀴즈 검색 API 구현
  src/main/kotlin/com/quizit/quiz/handler/QuizHandler.kt
  src/main/kotlin/com/quizit/quiz/repository/QuizRepository.kt
  src/main/kotlin/com/quizit/quiz/service/QuizService.kt
  src/test/kotlin/com/quizit/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/quizit/quiz/service/QuizServiceTest.kt
Labels: Feat

#41 [#40] 예외 처리 추가 및 전체적인 기능 점검
  src/main/kotlin/com/quizit/quiz/adapter/producer/QuizProducer.kt
  src/main/kotlin/com/quizit/quiz/dto/request/UpdateChapterByIdRequest.kt
  src/main/kotlin/com/quizit/quiz/service/ChapterService.kt
  src/main/kotlin/com/quizit/quiz/service/CourseService.kt
  src/main/kotlin/com/quizit/quiz/service/CurriculumService.kt
  src/main/kotlin/com/quizit/quiz/service/QuizService.kt
  src/test/kotlin/com/quizit/quiz/config/SecurityTestConfiguration.kt
  src/test/kotlin/com/quizit/quiz/controller/ChapterControllerTest.kt
  src/test/kotlin/com/quizit/quiz/controller/CourseControllerTest.kt
  src/test/kotlin/com/quizit/quiz/controller/CurriculumControllerTest.kt
  src/test/kotlin/com/quizit/quiz/controller/QuizControllerTest.kt
  src/test/kotlin/com/quizit/quiz/fixture/ChapterFixture.kt
  src/test/kotlin/com/quizit/quiz/fixture/CourseFixture.kt
  src/test/kotlin/com/quizit/quiz/fixture/CurriculumFixture.kt
  src/test/kotlin/com/quizit/quiz/fixture/QuizFixture.kt
  src/test/kotlin/com/quizit/quiz/fixture/UserFixture.kt
  src/test/kotlin/com/quizit/quiz/service/ChapterServiceTest.kt
  src/test/kotlin/com/quizit/quiz/service/CourseServiceTest.kt
  src/test/kotlin/com/quizit/quiz/service/QuizServiceTest.kt
Labels: Fix, Style, Refactor
